name: "Ten Outstanding Boy Scouts of the Philippines Association"
description: "Jekyll Introductory Project"

baseurl: "/tobspa-site"

paginate: 10

markdown: rdiscount
permalink: /:categories/:title
